### PR TITLE
Feature/map of maps

### PR DESCRIPTION
**Pull request by rodionovsasha**

### CODE REVIEW

**Comment by vkorobkov** [comment]
I see that you have extended `RowsLoader`, but I expected that you'll also add some public API method(s) into `JFixtures` class, so potentially Gropovy user's can send a map of tables and get the SQL on output:?

**Comment by rodionovsasha** [comment]
which methods do you expect to see?

**Comment by vkorobkov** [comment]
Up to you, but something like
```java
public JFixtures addTables(Map<...> ... tables);
```

**Comment by vkorobkov** [comment]
@rodionovsasha the PR looks good, but please add a new task to the board to handle these cases with `null`, `[]` and `[:]`. Probably we don't have to extend `MapTableLoader` for that, we can just introduce a new class which "purifies" the map of map of maps :)

**Review by vkorobkov — APPROVED** [review]

**Pull request merged**
